// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Runtime Version:4.0.30319.42000
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------


using System.Diagnostics;

namespace PrinterQueueWatch.My.Resources
{

    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [Microsoft.VisualBasic.HideModuleName()]
    internal static class Resources
    {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("PrinterQueueWatch.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Error.
        /// </summary>
        internal static string jsd_error
        {
            get
            {
                return ResourceManager.GetString("jsd_error", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Offline.
        /// </summary>
        internal static string jsd_offline
        {
            get
            {
                return ResourceManager.GetString("jsd_offline", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Out of Paper.
        /// </summary>
        internal static string jsd_paperout
        {
            get
            {
                return ResourceManager.GetString("jsd_paperout", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Paused.
        /// </summary>
        internal static string jsd_paused
        {
            get
            {
                return ResourceManager.GetString("jsd_paused", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Printed.
        /// </summary>
        internal static string jsd_printed
        {
            get
            {
                return ResourceManager.GetString("jsd_printed", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Printing.
        /// </summary>
        internal static string jsd_printing
        {
            get
            {
                return ResourceManager.GetString("jsd_printing", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Configuration File.
        /// </summary>
        internal static string pd_ts_ConfigurationFile
        {
            get
            {
                return ResourceManager.GetString("pd_ts_ConfigurationFile", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Data File.
        /// </summary>
        internal static string pd_ts_DataFile
        {
            get
            {
                return ResourceManager.GetString("pd_ts_DataFile", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Default Data Type.
        /// </summary>
        internal static string pd_ts_DefaultDataType
        {
            get
            {
                return ResourceManager.GetString("pd_ts_DefaultDataType", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Driver DLL.
        /// </summary>
        internal static string pd_ts_DriverPath
        {
            get
            {
                return ResourceManager.GetString("pd_ts_DriverPath", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Environment.
        /// </summary>
        internal static string pd_ts_Environment
        {
            get
            {
                return ResourceManager.GetString("pd_ts_Environment", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Help File.
        /// </summary>
        internal static string pd_ts_HelpFile
        {
            get
            {
                return ResourceManager.GetString("pd_ts_HelpFile", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Monitor Name.
        /// </summary>
        internal static string pd_ts_MonitorName
        {
            get
            {
                return ResourceManager.GetString("pd_ts_MonitorName", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Name.
        /// </summary>
        internal static string pd_ts_Name
        {
            get
            {
                return ResourceManager.GetString("pd_ts_Name", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Operating System Version.
        /// </summary>
        internal static string pd_ts_OperatingSystemVersion
        {
            get
            {
                return ResourceManager.GetString("pd_ts_OperatingSystemVersion", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Print job redirection failed.
        /// </summary>
        internal static string pem_JobTransferFailed
        {
            get
            {
                return ResourceManager.GetString("pem_JobTransferFailed", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Insufficient print job access rights.
        /// </summary>
        internal static string pem_NoJobAccess
        {
            get
            {
                return ResourceManager.GetString("pem_NoJobAccess", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Insufficient rights to pause printing.
        /// </summary>
        internal static string pem_NoPause
        {
            get
            {
                return ResourceManager.GetString("pem_NoPause", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Insufficient access rights.
        /// </summary>
        internal static string pem_NoPrinterAccess
        {
            get
            {
                return ResourceManager.GetString("pem_NoPrinterAccess", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Insufficient rights to resume printing.
        /// </summary>
        internal static string pem_NoResume
        {
            get
            {
                return ResourceManager.GetString("pem_NoResume", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Average Pages Per Month.
        /// </summary>
        internal static string pi_ts_AveragePagesPerMonth
        {
            get
            {
                return ResourceManager.GetString("pi_ts_AveragePagesPerMonth", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Comment.
        /// </summary>
        internal static string pi_ts_Comment
        {
            get
            {
                return ResourceManager.GetString("pi_ts_Comment", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Default Print Job Data Type.
        /// </summary>
        internal static string pi_ts_DefaultDataType
        {
            get
            {
                return ResourceManager.GetString("pi_ts_DefaultDataType", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Driver Name.
        /// </summary>
        internal static string pi_ts_DriverName
        {
            get
            {
                return ResourceManager.GetString("pi_ts_DriverName", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Default.
        /// </summary>
        internal static string pi_ts_is_IsDefault
        {
            get
            {
                return ResourceManager.GetString("pi_ts_is_IsDefault", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Network Printer.
        /// </summary>
        internal static string pi_ts_is_IsNetworkPrinter
        {
            get
            {
                return ResourceManager.GetString("pi_ts_is_IsNetworkPrinter", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Shared.
        /// </summary>
        internal static string pi_ts_is_IsShared
        {
            get
            {
                return ResourceManager.GetString("pi_ts_is_IsShared", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Count of Queued Jobs.
        /// </summary>
        internal static string pi_ts_JobCount
        {
            get
            {
                return ResourceManager.GetString("pi_ts_JobCount", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Location.
        /// </summary>
        internal static string pi_ts_Location
        {
            get
            {
                return ResourceManager.GetString("pi_ts_Location", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Not Default.
        /// </summary>
        internal static string pi_ts_not_IsDefault
        {
            get
            {
                return ResourceManager.GetString("pi_ts_not_IsDefault", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Local Printer.
        /// </summary>
        internal static string pi_ts_not_IsNetworkPrinter
        {
            get
            {
                return ResourceManager.GetString("pi_ts_not_IsNetworkPrinter", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Not Shared.
        /// </summary>
        internal static string pi_ts_not_IsShared
        {
            get
            {
                return ResourceManager.GetString("pi_ts_not_IsShared", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string pi_ts_Parameters
        {
            get
            {
                return ResourceManager.GetString("pi_ts_Parameters", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Port.
        /// </summary>
        internal static string pi_ts_PortName
        {
            get
            {
                return ResourceManager.GetString("pi_ts_PortName", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Printer Name.
        /// </summary>
        internal static string pi_ts_PrinterName
        {
            get
            {
                return ResourceManager.GetString("pi_ts_PrinterName", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Print Processor.
        /// </summary>
        internal static string pi_ts_PrintProcessor
        {
            get
            {
                return ResourceManager.GetString("pi_ts_PrintProcessor", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Default Print Job Priority.
        /// </summary>
        internal static string pi_ts_Priority
        {
            get
            {
                return ResourceManager.GetString("pi_ts_Priority", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Job Seperator Filename.
        /// </summary>
        internal static string pi_ts_SeperatorFilename
        {
            get
            {
                return ResourceManager.GetString("pi_ts_SeperatorFilename", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Server Name.
        /// </summary>
        internal static string pi_ts_ServerName
        {
            get
            {
                return ResourceManager.GetString("pi_ts_ServerName", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Shared As.
        /// </summary>
        internal static string pi_ts_ShareName
        {
            get
            {
                return ResourceManager.GetString("pi_ts_ShareName", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Time Restriction.
        /// </summary>
        internal static string pi_ts_TimeWindow
        {
            get
            {
                return ResourceManager.GetString("pi_ts_TimeWindow", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Copies.
        /// </summary>
        internal static string pj_ts_Copies
        {
            get
            {
                return ResourceManager.GetString("pj_ts_Copies", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Data Type.
        /// </summary>
        internal static string pj_ts_DataType
        {
            get
            {
                return ResourceManager.GetString("pj_ts_DataType", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Document.
        /// </summary>
        internal static string pj_ts_Document
        {
            get
            {
                return ResourceManager.GetString("pj_ts_Document", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Printer Driver.
        /// </summary>
        internal static string pj_ts_Drivername
        {
            get
            {
                return ResourceManager.GetString("pj_ts_Drivername", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Color.
        /// </summary>
        internal static string pj_ts_is_Color
        {
            get
            {
                return ResourceManager.GetString("pj_ts_is_Color", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Landscape.
        /// </summary>
        internal static string pj_ts_is_Landscape
        {
            get
            {
                return ResourceManager.GetString("pj_ts_is_Landscape", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Job Size (in Bytes).
        /// </summary>
        internal static string pj_ts_JobSize
        {
            get
            {
                return ResourceManager.GetString("pj_ts_JobSize", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Machine.
        /// </summary>
        internal static string pj_ts_MachineName
        {
            get
            {
                return ResourceManager.GetString("pj_ts_MachineName", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Black and White.
        /// </summary>
        internal static string pj_ts_not_Color
        {
            get
            {
                return ResourceManager.GetString("pj_ts_not_Color", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Potrait.
        /// </summary>
        internal static string pj_ts_not_Landscape
        {
            get
            {
                return ResourceManager.GetString("pj_ts_not_Landscape", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Notify User.
        /// </summary>
        internal static string pj_ts_NotifyUserName
        {
            get
            {
                return ResourceManager.GetString("pj_ts_NotifyUserName", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Pages Printed.
        /// </summary>
        internal static string pj_ts_PagesPrinted
        {
            get
            {
                return ResourceManager.GetString("pj_ts_PagesPrinted", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Paper Type.
        /// </summary>
        internal static string pj_ts_PaperKind
        {
            get
            {
                return ResourceManager.GetString("pj_ts_PaperKind", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Page Length.
        /// </summary>
        internal static string pj_ts_PaperLength
        {
            get
            {
                return ResourceManager.GetString("pj_ts_PaperLength", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Paper Source.
        /// </summary>
        internal static string pj_ts_PaperSource
        {
            get
            {
                return ResourceManager.GetString("pj_ts_PaperSource", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Page Width.
        /// </summary>
        internal static string pj_ts_PaperWidth
        {
            get
            {
                return ResourceManager.GetString("pj_ts_PaperWidth", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string pj_ts_Parameters
        {
            get
            {
                return ResourceManager.GetString("pj_ts_Parameters", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Position in Queue.
        /// </summary>
        internal static string pj_ts_Position
        {
            get
            {
                return ResourceManager.GetString("pj_ts_Position", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Printer.
        /// </summary>
        internal static string pj_ts_PrinterName
        {
            get
            {
                return ResourceManager.GetString("pj_ts_PrinterName", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Resolution.
        /// </summary>
        internal static string pj_ts_PrinterResolutionKind
        {
            get
            {
                return ResourceManager.GetString("pj_ts_PrinterResolutionKind", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Horizontal Resolution.
        /// </summary>
        internal static string pj_ts_PrinterResolutionX
        {
            get
            {
                return ResourceManager.GetString("pj_ts_PrinterResolutionX", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Vertical Resolution.
        /// </summary>
        internal static string pj_ts_PrinterResolutionY
        {
            get
            {
                return ResourceManager.GetString("pj_ts_PrinterResolutionY", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Print Processor.
        /// </summary>
        internal static string pj_ts_PrintProcessorName
        {
            get
            {
                return ResourceManager.GetString("pj_ts_PrintProcessorName", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Priority.
        /// </summary>
        internal static string pj_ts_Priority
        {
            get
            {
                return ResourceManager.GetString("pj_ts_Priority", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Time in Queue.
        /// </summary>
        internal static string pj_ts_QueuedTime
        {
            get
            {
                return ResourceManager.GetString("pj_ts_QueuedTime", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Status.
        /// </summary>
        internal static string pj_ts_StatusDescription
        {
            get
            {
                return ResourceManager.GetString("pj_ts_StatusDescription", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Submitted.
        /// </summary>
        internal static string pj_ts_Submitted
        {
            get
            {
                return ResourceManager.GetString("pj_ts_Submitted", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Print Time Restriction.
        /// </summary>
        internal static string pj_ts_TimeWindow
        {
            get
            {
                return ResourceManager.GetString("pj_ts_TimeWindow", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Total Pages.
        /// </summary>
        internal static string pj_ts_TotalPages
        {
            get
            {
                return ResourceManager.GetString("pj_ts_TotalPages", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to User.
        /// </summary>
        internal static string pj_ts_UserName
        {
            get
            {
                return ResourceManager.GetString("pj_ts_UserName", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Cannot cancel print job.
        /// </summary>
        internal static string pjerr_cancel
        {
            get
            {
                return ResourceManager.GetString("pjerr_cancel", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Cannot delete print job.
        /// </summary>
        internal static string pjerr_delete
        {
            get
            {
                return ResourceManager.GetString("pjerr_delete", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Cannot update print job.
        /// </summary>
        internal static string pjerr_update
        {
            get
            {
                return ResourceManager.GetString("pjerr_update", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to From.
        /// </summary>
        internal static string tw_ts_From
        {
            get
            {
                return ResourceManager.GetString("tw_ts_From", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Unrestricted.
        /// </summary>
        internal static string tw_ts_Unrestricted
        {
            get
            {
                return ResourceManager.GetString("tw_ts_Unrestricted", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Until.
        /// </summary>
        internal static string tw_ts_Until
        {
            get
            {
                return ResourceManager.GetString("tw_ts_Until", resourceCulture);
            }
        }
    }
}